{% set name = "iscd-commons" %}
{% set version = "1.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # there are no tagged releases which so using archives of specific commits
  url: https://github.com/ISCDtoolbox/Commons/archive/refs/tags/v{{ version }}.zip
  sha256: 2d6e4f02852146609efbb9288b70ca5b6763e6b2ac61fffc64ebd303a3577896
  patches:
    - CMakeLists_conda.patch
build:
  number: 2
  skip: true  # [py<3]
  run_exports:
    - {{ pin_subpackage('iscd-commons', max_pin='x.x.x') }}

requirements:
  build:
      - {{ compiler('c') }}  # [not win]
      - {{ compiler('m2w64_c') }}  # [win]
  host:
    - cmake
    - make  # [not win]
    - ninja  # [win]
  run:
    - m2w64-libwinpthread-git  # [win]

test:
  commands:
    - test -f $PREFIX/lib/libCommons.so  # [linux]
    - test -f $PREFIX/lib/libCommons.dylib  # [osx]
    - if not exist %LIBRARY_LIB%\\libCommons.dll exit 1  # [win]
    - test -f $PREFIX/include/chrono.h  # [unix]
    - test -f $PREFIX/include/eigen.h  # [unix]
    - test -f $PREFIX/include/libmesh5.h  # [unix]        
    - test -f $PREFIX/include/lplib3.h  # [unix]
    - test -f $PREFIX/include/sparse.h  # [unix]
    - if not exist %LIBRARY_INC%\\chrono.h exit 1  # [win]
    - if not exist %LIBRARY_INC%\\eigen.h exit 1  # [win]
    - if not exist %LIBRARY_INC%\\libmesh5.h exit 1  # [win]
    - if not exist %LIBRARY_INC%\\lplib3.h exit 1  # [win]
    - if not exist %LIBRARY_INC%\\sparse.h exit 1  # [win]

about:
  home: https://iscd.sorbonne-universite.fr/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'ISCD - Commons library'
  description: |
    Common codes used for ISCD softwares (Linear algebra, Chrono, I/O...)
  doc_url: https://github.com/ISCDtoolbox/Commons/blob/master/README.md
  dev_url: https://github.com/ISCDtoolbox/Commons 

extra:
  recipe-maintainers:
    - ldallolio
    - fbordeu
